title: Mamesa El
logo: "images/mamesa_headshot_2.jpg"
description: >
  I am a recent graduate with a Master's in Data Science from UC Berkeley, where I developed a strong foundation in programming, mathematics, and physics. My recent experience as a Data Scientist at TextVolt, an SMS solution company, has further honed my skills. I am passionate about applying my expertise to tackle complex challenges in technology and industries where a deep understanding of physics is crucial.
  
  View My LinkedIn Profile: [LinkedIn Profile](https://www.linkedin.com/in/example/)

technical_proficiencies:
  Programming_and_Data_Analysis:
    - Python
    - Jupyter Notebook
  Version_Control_and_Collaboration:
    - GitHub
  Containerization_and_Virtualization:
    - Docker
    - Kubernetes
  Databases_and_Data_Caching:
    - Redis
  Machine_Learning_Operations:
    - ML Flow
  Cloud_Computing_and_Big_Data_Platforms:
    - Azure
    - Databricks

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: UA-000000-0
