title: "Mamesa El"
logo: "images/mamesa_headshot_2.jpg"
description: >
  I am a recent graduate with a Master's in Data Science from UC Berkeley, where I developed a strong foundation in programming, mathematics, and physics. My experience as a Data Scientist at TextVolt has honed my skills further. Passionate about tackling complex tech challenges, especially in industries where deep physics understanding is key.
  
  # Insert second description here as needed without <br> tags.

  View my LinkedIn profile here: [LinkedIn Profile](https://www.linkedin.com/in/example/)

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: "UA-000000-0"

# Additional sections as headers
about_me: "Your about me section here."
experience: "Your experience section here."
connect: "Your connection details or instructions here."
skills: "Your skills list here."
analytics: "Your Google Analytics tracking ID here."
